export = [
  {
    name: "Everton",
    email: "everton@email.com",
    coach: "Tega",
    country: "England",
    founded: 1984,
    stadium_name: "shielfield",
    wins: 13,
    losses: 10,
    goals: 23,
    stadium_capacity: "30000m"
  },
  {
    name: "Aston Villa",
    email: "aston@email.com",
    coach: "Ibrahim",
    country: "England",
    founded: 1989,
    stadium_name: "aston field",
    wins: 9,
    losses: 12,
    goals: 15,
    stadium_capacity: "40000m"
  },
  {
    name: "Chelsea",
    email: "chelsea@email.com",
    coach: "amak",
    country: "England",
    founded: 1980,
    stadium_name: "old traford",
    wins: 18,
    losses: 9,
    goals: 32,
    stadium_capacity: "35000m"
  },
  {
    name: "Manchester City",
    email: "mancity@email.com",
    coach: "williams",
    country: "England",
    founded: 1978,
    stadium_name: "old traford",
    wins: 19,
    losses: 5,
    goals: 36,
    stadium_capacity: "44000m"
  },
  {
    name: "Arsena",
    email: "arsena@email.com",
    coach: "Rukee",
    country: "England",
    founded: 1976,
    stadium_name: "arsenalfield",
    wins: 14,
    losses: 12,
    goals: 21,
    stadium_capacity: "40000m"
  },
  {
    name: "Liverpool",
    email: "liverpool@email.com",
    coach: "Bash",
    country: "England",
    founded: 1987,
    stadium_name: "liverpool field",
    wins: 20,
    losses: 7,
    goals: 29,
    stadium_capacity: "60000m"
  },
  {
    name: "Lechester city",
    email: "lechester@email.com",
    coach: "Izu",
    country: "England",
    founded: 1990,
    stadium_name: "city traford",
    wins: 8,
    losses: 15,
    goals: 10,
    stadium_capacity: "38000m"
  },
  {
    name: "Manchester United",
    email: "manu@email.com",
    coach: "Dee",
    country: "England",
    founded: 1968,
    stadium_name: "old traford",
    wins: 19,
    losses: 9,
    goals: 25,
    stadium_capacity: "49000m"
  },
  {
    name: "Bolton",
    email: "bolton@email.com",
    coach: "Austine",
    country: "England",
    founded: 1980,
    stadium_name: "bolton field",
    wins: 17,
    losses: 13,
    goals: 17,
    stadium_capacity: "30000m"
  },
  {
    name: "Brimingham City",
    email: "brimiham@email.com",
    coach: "ochuko",
    country: "England",
    founded: 1998,
    stadium_name: "camp nou",
    wins: 16,
    losses: 18,
    goals: 20,
    stadium_capacity: "50000m"
  },
  {
    name: "Cardiff City",
    email: "cardiff@email.com",
    coach: "Bash",
    country: "England",
    founded: 1987,
    stadium_name: "liverpool field",
    wins: 9,
    losses: 16,
    goals: 11,
    stadium_capacity: "60000m"
  },
  {
    name: "Crystal Palace",
    email: "crystal@email.com",
    coach: "Jones",
    country: "England",
    founded: 1990,
    stadium_name: "city traford",
    wins: 14,
    losses: 16,
    goals: 17,
    stadium_capacity: "38000m"
  },
  {
    name: "Fulham",
    email: "fulham@email.com",
    coach: "Van gwart",
    country: "England",
    founded: 1968,
    stadium_name: "old traford",
    wins: 10,
    losses: 19,
    goals: 11,
    stadium_capacity: "49000m"
  },
  {
    name: "Hull City",
    email: "hullCity@email.com",
    coach: "Austine",
    country: "England",
    founded: 1980,
    stadium_name: "bolton field",
    wins: 17,
    losses: 13,
    goals: 22,
    stadium_capacity: "30000m"
  },
  {
    name: "Norwich City",
    email: "norwich@email.com",
    coach: "ochuko",
    country: "England",
    founded: 1998,
    stadium_name: "camp nou",
    wins: 4,
    losses: 20,
    goals: 7,
    stadium_capacity: "50000m"
  }
];
